apiVersion: apps/v1
kind: Deployment
metadata:
  name: coredns
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-dns
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - name: coredns
        image: k8s.gcr.io/coredns/coredns:1.8.4
        resources:
          limits:
            memory: 1700Mi
          requests:
            cpu: 1000m
            memory: 700Mi
        args:
        - -conf
        - /etc/coredns/Corefile
        - -log
        - /dev/stderr
        volumeMounts:
        - name: config-volume
          mountPath: /etc/coredns
      volumes:
      - name: config-volume
        configMap:
          name: coredns
          items:
          - key: Corefile
            path: Corefile
