apiVersion: v1
kind: Service
metadata:
  name: eventprocessor-svc
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: eventprocessor
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eventprocessor
  name: eventprocessor-deployment
  namespace: argocd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventprocessor
  template:
    metadata:
      labels:
        app: eventprocessor
    spec:
      containers:
        - name: my-container
          ports:
            - containerPort: 8080
      - env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              key: db-host
              name: my-app-secret
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: db-user
              name: my-app-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: db-password
              name: my-app-secret
        image: 853697862182.dkr.ecr.us-east-1.amazonaws.com/portal-orgmgt-eventprocessor-ap
